### ISSUE TITLE
bug: pip install fails when trying to build wheel

### ISSUE THREAD

**Issue by tommydogs** [aarnphm/whispercpp#217]
### Describe the bug

Started with new install Pi Lite 32-bit (Bookworm)
Did update and upgrade
Installed suggested packages for Pi Lite install
Installed git as well
Started virtual environment and ran pip install: pip install git+https://github.com/AIWintermuteAI/whispercpp.git -vv
Ends with error message: Building wheel for whispercpp (pyproject.toml) did not run successfully

### To reproduce

Updating files:  97% (100/103)
  Updating files:  98% (101/103)
  Updating files:  99% (102/103)
  Updating files: 100% (103/103)
  Updating files: 100% (103/103), done.
  Running command git rev-parse HEAD
  d549400b7480db936d669bb0039e188bad134cd9
  Resolved https://github.com/AIWintermuteAI/whispercpp.git to commit d549400b7480db936d669bb0039e188bad134cd9
  Running command git submodule update --init --recursive -q
  Running command git rev-parse HEAD
  d549400b7480db936d669bb0039e188bad134cd9
  Added git+https://github.com/AIWintermuteAI/whispercpp.git to build tracker '/tmp/pip-build-tracker-i3li3j6f'
  Created temporary directory: /tmp/pip-build-env-rq_g2ucy
  Running command pip subprocess to install build dependencies
  Using pip 23.0.1 from /home/rayray/whisper/lib/python3.11/site-packages/pip (python 3.11)
  Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
  Collecting setuptools>=65
    Downloading https://www.piwheels.org/simple/setuptools/setuptools-75.1.0-py3-none-any.whl (1.2 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.4 MB/s eta 0:00:00
  Collecting setuptools_scm[toml]>=7
    Downloading https://www.piwheels.org/simple/setuptools-scm/setuptools_scm-8.1.0-py3-none-any.whl (43 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 3.0 MB/s eta 0:00:00
  Collecting wheel
    Downloading https://www.piwheels.org/simple/wheel/wheel-0.44.0-py3-none-any.whl (67 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 3.6 MB/s eta 0:00:00
  Collecting packaging>=20
    Downloading https://www.piwheels.org/simple/packaging/packaging-24.1-py3-none-any.whl (53 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 kB 3.6 MB/s eta 0:00:00
  Installing collected packages: wheel, setuptools, packaging, setuptools_scm
    Creating /tmp/pip-build-env-rq_g2ucy/overlay/bin
    changing mode of /tmp/pip-build-env-rq_g2ucy/overlay/bin/wheel to 755
  Successfully installed packaging-24.1 setuptools-75.1.0 setuptools_scm-8.1.0 wheel-0.44.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  creating src/whispercpp.egg-info
  writing src/whispercpp.egg-info/PKG-INFO
  writing dependency_links to src/whispercpp.egg-info/dependency_links.txt
  writing top-level names to src/whispercpp.egg-info/top_level.txt
  writing manifest file 'src/whispercpp.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'src/whispercpp.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Created temporary directory: /tmp/pip-modern-metadata-6ambnnk3
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-6ambnnk3/whispercpp.egg-info
  writing /tmp/pip-modern-metadata-6ambnnk3/whispercpp.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-6ambnnk3/whispercpp.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-modern-metadata-6ambnnk3/whispercpp.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-6ambnnk3/whispercpp.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-6ambnnk3/whispercpp.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-6ambnnk3/whispercpp-0.0.post411+gd549400.dist-info'
  Preparing metadata (pyproject.toml) ... done
  Source in /tmp/pip-req-build-dcxla_6n has version 0.0.post411+gd549400, which satisfies requirement whispercpp==0.0.post411+gd549400 from git+https://github.com/AIWintermuteAI/whispercpp.git
  Removed whispercpp==0.0.post411+gd549400 from git+https://github.com/AIWintermuteAI/whispercpp.git from build tracker '/tmp/pip-build-tracker-i3li3j6f'
Created temporary directory: /tmp/pip-unpack-zc5kjke0
Building wheels for collected packages: whispercpp
  Created temporary directory: /tmp/pip-wheel-k0le000t
  Destination directory: /tmp/pip-wheel-k0le000t
  Running command Building wheel for whispercpp (pyproject.toml)
  running bdist_wheel
  INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 6.0.0 will be used instead of system-wide bazel installation.
  Downloading bazel, will try URLs: https://storage.googleapis.com/grpc-bazel-mirror/github.com/bazelbuild/bazel/releases/download/6.0.0/bazel-6.0.0-linux-arm64 https://github.com/bazelbuild/bazel/releases/download/6.0.0/bazel-6.0.0-linux-arm64
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed

    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0   255    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (22) The requested URL returned error: 404
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed

    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

    0  151M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    6  151M    6 10.4M    0     0  6429k      0  0:00:24  0:00:01  0:00:23 12.9M
   15  151M   15 23.1M    0     0  8930k      0  0:00:17  0:00:02  0:00:15 12.8M
   23  151M   23 35.6M    0     0  9966k      0  0:00:15  0:00:03  0:00:12 12.6M
   32  151M   32 49.4M    0     0  10.6M      0  0:00:14  0:00:04  0:00:10 12.9M
   41  151M   41 62.9M    0     0  10.9M      0  0:00:13  0:00:05  0:00:08 12.8M
   48  151M   48 74.3M    0     0  11.1M      0  0:00:13  0:00:06  0:00:07 12.7M
   58  151M   58 88.2M    0     0  11.5M      0  0:00:13  0:00:07  0:00:06 13.0M
   66  151M   66  101M    0     0  11.7M      0  0:00:12  0:00:08  0:00:04 13.1M
   75  151M   75  114M    0     0  11.8M      0  0:00:12  0:00:09  0:00:03 12.9M
   82  151M   82  124M    0     0  11.7M      0  0:00:12  0:00:10  0:00:02 12.6M
   87  151M   87  133M    0     0  11.4M      0  0:00:13  0:00:11  0:00:02 11.7M
   96  151M   96  146M    0     0  11.6M      0  0:00:13  0:00:12  0:00:01 11.7M
  100  151M  100  151M    0     0  11.6M      0  0:00:13  0:00:13 --:--:-- 11.4M
  /tmp/pip-req-build-dcxla_6n/tools/bazel: line 67: /tmp/pip-req-build-dcxla_6n/tools/bazel-6.0.0-linux-arm64: cannot execute: required file not found
  Building pybind11 extension...
  Traceback (most recent call last):
    File "/home/rayray/whisper/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/rayray/whisper/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/rayray/whisper/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 421, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 45, in <module>
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-rq_g2ucy/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "<string>", line 28, in run
    File "<string>", line 23, in compile_ext
    File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/tmp/pip-req-build-dcxla_6n/tools/bazel', 'run', '//:extensions']' returned non-zero exit status 127.
  error: subprocess-exited-with-error

  × Building wheel for whispercpp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/rayray/whisper/bin/python3 /home/rayray/whisper/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp24s5dcqn
  cwd: /tmp/pip-req-build-dcxla_6n
  Building wheel for whispercpp (pyproject.toml) ... error
  ERROR: Failed building wheel for whispercpp
Failed to build whispercpp
ERROR: Could not build wheels for whispercpp, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/home/rayray/whisper/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/rayray/whisper/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rayray/whisper/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 477, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for whispercpp, which is required to install pyproject.toml-based projects
Removed build tracker: '/tmp/pip-build-tracker-i3li3j6f'

### Environment

python3.11.2
Raspi Lite 32-bit (Bookworm)

**Comment by tommydogs** [comment]
Sorry, wrong github....supposed to be AIWintermuteAI
