### ISSUE TITLE
bug:  linux wheel Import Error

### ISSUE THREAD

**Issue by zhqu1148980644** [aarnphm/whispercpp#77]
### Describe the bug

```
Python 3.11.2 (main, Mar 23 2023, 17:12:29) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from whispercpp import Whisper
>>>
>>> w = Whisper.from_pretrained("tiny.en")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/whispercpp/__init__.py", line 105, in from_pretrained
    context = api.Context.from_file(
              ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/whispercpp/utils.py", line 144, in __getattr__
    self._module = self._load()
                   ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/whispercpp/utils.py", line 122, in _load
    module = importlib.import_module(self.__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/lib/python3.11/site-packages/whispercpp/api_cpp2py_export.so)
```

### To reproduce

Run above codes in docker container with image: `python:3`

### Environment

python: 3.11
platform: x86-64 Debian GNU/Linux 11 (bullseye)

**Comment by sorgfresser** [comment]
Had that one too. This bug is not caused by the bindings but by whisper.cpp I suppose. It is simply linked to your Distro-Version being outdated by now. I had this first on Linux Mint Una, it was fixed by upgrading to 21.

**Comment by yanchujian** [comment]
> Had that one too. This bug is not caused by the bindings but by whisper.cpp I suppose. It is simply linked to your Distro-Version being outdated by now. I had this first on Linux Mint Una, it was fixed by upgrading to 21.

Hello,what does the 21 version here refer to.

**Comment by sorgfresser** [comment]
The linux mint version 21, i.e. Vanessa. This bug should relate to some .so files being outdated. You could either manually upgrade this or dump your distro.

**Comment by Nik-Kras** [comment]
I had the same problem. Whenever I attempted loading a model - I got "Illegal instruction (core dumped)".
Here I found the the issue could be in the CPU and it worked for me.

I got this error on a server with Xeon E5-2687W CPU (manufactured back in 2012)
When I changed it to AMD Ryzen Threadripper PRO 5955WX (2022) - all worked fine.

If that doesn't help you, I also found that it could be a bug with numpy, try downgrading in to 1.19.4
