### ISSUE TITLE
Erron when running on Debian ARM64

### ISSUE THREAD

**Issue by lucianomotti** [aarnphm/whispercpp#84]
Hi,

I'm trying to run the code from a Debian ARM64 on AWS.

After installing using **pip install whispercpp**, I executed the following code:

```
from whispercpp import Whisper

print(f'STT Starting')
w = Whisper.from_pretrained("tiny")
w.transcribe_from_file("/etc/stt/audio.wav")
```

And it fails with this trace:

```
STT Starting
Traceback (most recent call last):
  File "/etc/stt/stt.py", line 4, in <module>
    w = Whisper.from_pretrained("tiny")
  File "/usr/local/lib/python3.9/dist-packages/whispercpp/__init__.py", line 105, in from_pretrained
    context = api.Context.from_file(
  File "/usr/local/lib/python3.9/dist-packages/whispercpp/utils.py", line 144, in __getattr__
    self._module = self._load()
  File "/usr/local/lib/python3.9/dist-packages/whispercpp/utils.py", line 122, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1108, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.9/dist-packages/whispercpp/api_cpp2py_export.so: invalid ELF header

```

Am I missing something?

**Comment by aarnphm** [comment]
oh this arm wheels is broken. what version of the package you are using?

**Comment by aarnphm** [comment]
can you try to do `pip install git+https://github.com/aarnphm/whispercpp.git` for now?

**Comment by codethazine** [comment]
Hey I'm having the same issue on ARM64 (specifically Jetson Nano)
